name: Test

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Cache cargo
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo
    - name: Install toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly-2020-05-07
        components: rustfmt, clippy
        target: wasm32-unknown-unknown
        override: true
        default: true
    - name: Show rustc version
      run: rustc --version
    - name: Show clippy version
      run: cargo clippy --version
    - name: Install Wasm toolchain
      run: rustup target add wasm32-unknown-unknown
    - name: Check format
      run: make dev-format-check
    - name: TEMP cargo clean
      run: cargo clean
    - name: TEMP cargo check
      run: cargo check --all
    - name: Run clippy
      run: cargo clippy -- -D warnings
    - name: Update
      run: cargo update
    - name: Check for Wasm
      run: make dev-check
    - name: Run tests
      run: make dev-test
